[build]
  command = "rm -rf .cache && cd site && npm run build"
  publish = "public"

[build.environment]
  GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES = "true"
  GATSBY_INCREMENTAL_BUILDS = "true"