[build]
  base = "site"
  command = "cd site && gatsby clean && npm run build"
  publish = "site/public"  # build çıktısının site/public içinde olduğunu belirtir


[build.environment]
  GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES = "true"
  GATSBY_INCREMENTAL_BUILDS = "true"